import { app, BrowserWindow, ipcMain, screen, globalShortcut, shell, Tray, Menu, nativeImage } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { log } from './logger';
import { clipboardService } from './services/clipboard';
import { dictionaryService } from './services/dictionary';
import { wikipediaService } from './services/wikipedia';
import { searchService } from './services/search';
import { createNativeSelectionService, SelectionEvent } from './services/native-selection';
import { contextCaptureHub, ContextEvent, selectionToContext } from './services/context-capture';
import { captureScreenRegion, captureAroundPoint } from './services/screen-capture';
import { ocrEngine, textNearPoint } from './services/ocr-engine';
import { isLookupWorthy } from './services/text-normalize';
import { HoverLookupService, phevereWindowFocused } from './services/hover-lookup';
import { placePopupNearPoint } from './services/popup-placement';
import { showWorkProgress, updateWorkProgress, closeWorkProgress } from './services/work-progress';
import { isAcceleratorPhysicallyHeld } from './services/accelerator-key-state';
import { getForegroundWindowBoundsDip } from './services/foreground-window';
import { getNowPlaying, formatNowPlayingQuery } from './services/media-session';
import { readClipboardImage, loadImageFileAsPng, pngFromBase64 } from './services/clipboard-image';
import {
  loadMonitorSettings,
  saveMonitorSettingsFile,
  mergeMonitorSettings,
  monitorDefaults,
  MonitorMode,
  MonitorSettings,
} from './services/monitor-settings-store';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const POPUP_WINDOW_WEBPACK_ENTRY: string;
declare const OCR_OVERLAY_WEBPACK_ENTRY: string;
declare const OCR_OVERLAY_PRELOAD_WEBPACK_ENTRY: string;

// Check administrator privileges for UIAutomation
function checkAdminPrivileges(): boolean {
  try {
    const { execSync } = require('child_process');
    execSync('net session', { stdio: 'ignore' });
    return true;
  } catch (error) {
    return false;
  }
}

// Global variables
let mainWindow: BrowserWindow | null = null;
let popupWindows: BrowserWindow[] = [];
let settingsWindow: BrowserWindow | null = null;
let externalWindows: BrowserWindow[] = []; // Track external windows opened by the app
let tray: Tray | null = null;
let appIsQuitting = false;
/** Native UIA hook is running (needed for both "on" and "shortcut" modes). */
let nativeSelectionActive = false;
let monitorSettings: MonitorSettings = { ...monitorDefaults };
let registeredCycleAccelerator: string | null = null;
let registeredTriggerAccelerator: string | null = null;
let registeredOcrAccelerator: string | null = null;
let registeredHoverAccelerator: string | null = null;
let registeredGrabAccelerator: string | null = null;
let registeredReadWindowAccelerator: string | null = null;
let registeredClipboardOcrAccelerator: string | null = null;
let registeredMediaAccelerator: string | null = null;
let lastClipboardImageHash: string | null = null;
let clipboardImageWatchTimer: NodeJS.Timeout | null = null;
/** Max age of last selection for "select text, then press trigger" (ms). */
const TRIGGER_AFTER_SELECTION_MAX_MS = 60_000;
let nativeSelectionHandlerRegistered = false;
let lastSelectedText = '';
let lastSelectionEvent: ContextEvent | null = null;
let lastPopupText: string = '';
let lastPopupAt: number = 0;
let ocrOverlayWindow: BrowserWindow | null = null;
let contextHubWired = false;
let hoverLookup: HoverLookupService | null = null;

// Native selection service
const nativeSelectionService = createNativeSelectionService();

function broadcastMonitorMode(): void {
  try {
    mainWindow?.webContents.send('monitor-mode-changed', { mode: monitorSettings.mode });
  } catch {
    /* ignore */
  }
}

function setMonitoringMode(mode: MonitorMode): void {
  if (monitorSettings.mode === mode) {
    return;
  }
  monitorSettings = mergeMonitorSettings({ mode }, monitorSettings);
  saveMonitorSettingsFile(monitorSettings);
  applyMonitoringFromMode();
  syncGlobalMonitorShortcuts();
  broadcastMonitorMode();
  updateTrayContextMenu();
}

function cycleMonitoringMode(): void {
  const order: MonitorMode[] = ['off', 'on', 'shortcut'];
  const i = order.indexOf(monitorSettings.mode);
  const next = order[(i + 1) % order.length];
  
  // Defer state change to prevent re-entrancy crash during globalShortcut callback
  setTimeout(() => {
    setMonitoringMode(next);
  }, 0);
}

function unregisterCycleMonitorShortcut(): void {
  if (registeredCycleAccelerator) {
    try {
      globalShortcut.unregister(registeredCycleAccelerator);
    } catch {
      /* ignore */
    }
    registeredCycleAccelerator = null;
  }
}

function unregisterTriggerShortcut(): void {
  if (registeredTriggerAccelerator) {
    try {
      globalShortcut.unregister(registeredTriggerAccelerator);
    } catch {
      /* ignore */
    }
    registeredTriggerAccelerator = null;
  }
}

/** Re-register cycle shortcut (always) and trigger shortcut (shortcut mode only). */
function syncGlobalMonitorShortcuts(): void {
  unregisterCycleMonitorShortcut();
  unregisterTriggerShortcut();

  const acc = monitorSettings.cycleShortcut;
  const ok = globalShortcut.register(acc, () => {
    cycleMonitoringMode();
  });
  if (ok) {
    registeredCycleAccelerator = acc;
  } else {
    log.warn('main', 'Failed to register cycle monitor shortcut', { acc });
  }

  if (monitorSettings.mode === 'shortcut') {
    const accTrigger = monitorSettings.triggerShortcut;
    const okTrigger = globalShortcut.register(accTrigger, () => {
      onTriggerShortcutAfterSelection();
    });
    if (okTrigger) {
      registeredTriggerAccelerator = accTrigger;
    } else {
      log.warn('main', 'Failed to register trigger shortcut', { acc: accTrigger });
    }
  }
}

function onTriggerShortcutAfterSelection(): void {
  if (monitorSettings.mode !== 'shortcut') {
    return;
  }
  const now = Date.now();
  // Avoid second open when global hotkey fires right after "hold trigger while selecting"
  // (selection path already committed lastPopupAt synchronously).
  if (lastPopupAt && now - lastPopupAt < 450) {
    log.debug('main', 'Trigger shortcut: skip (popup just opened)');
    return;
  }
  const ev = lastSelectionEvent;
  if (!ev || !String(ev.text || '').trim()) {
    log.debug('main', 'Trigger shortcut: no stored selection');
    return;
  }
  const age = now - ev.timestamp;
  if (age > TRIGGER_AFTER_SELECTION_MAX_MS) {
    log.debug('main', 'Trigger shortcut: selection too old', { ageMs: age });
    return;
  }
  createPopupWindow(ev.x, ev.y);
}

function unregisterAccel(current: string | null): void {
  if (!current) return;
  try {
    globalShortcut.unregister(current);
  } catch {
    /* ignore */
  }
}

function registerOrWarn(acc: string, handler: () => void, label: string): string | null {
  try {
    const ok = globalShortcut.register(acc, handler);
    if (ok) return acc;
    log.warn('main', 'Failed to register shortcut', { label, acc });
  } catch (error) {
    log.warn('main', 'Exception registering shortcut', { label, acc, err: String(error) });
  }
  return null;
}

/** OCR / hover / grab / media shortcuts from settings + fixed clipboard-history. */
function syncFixedAppShortcuts(): void {
  unregisterAccel(registeredOcrAccelerator);
  unregisterAccel(registeredHoverAccelerator);
  unregisterAccel(registeredGrabAccelerator);
  unregisterAccel(registeredReadWindowAccelerator);
  unregisterAccel(registeredClipboardOcrAccelerator);
  unregisterAccel(registeredMediaAccelerator);
  registeredOcrAccelerator = null;
  registeredHoverAccelerator = null;
  registeredGrabAccelerator = null;
  registeredReadWindowAccelerator = null;
  registeredClipboardOcrAccelerator = null;
  registeredMediaAccelerator = null;

  registeredOcrAccelerator = registerOrWarn(
    monitorSettings.ocrShortcut,
    () => {
      if (ocrOverlayWindow && !ocrOverlayWindow.isDestroyed()) {
        closeOcrOverlay();
        log.info('main', 'OCR ROI overlay cancelled via shortcut');
        return;
      }
      void startOcrRegionCapture();
    },
    'ocr',
  );

  registeredHoverAccelerator = registerOrWarn(
    monitorSettings.hoverShortcut,
    () => setHoverEnabled(!monitorSettings.hoverEnabled),
    'hover',
  );

  registeredGrabAccelerator = registerOrWarn(
    'CommandOrControl+Shift+G',
    () => void grabOcrUnderCursor(),
    'grab',
  );

  registeredReadWindowAccelerator = registerOrWarn(
    'CommandOrControl+Shift+W',
    () => void readForegroundWindowOcr(),
    'read-window',
  );

  registeredClipboardOcrAccelerator = registerOrWarn(
    'CommandOrControl+Shift+I',
    () => void ocrClipboardImage(),
    'clipboard-ocr',
  );

  registeredMediaAccelerator = registerOrWarn(
    'CommandOrControl+Shift+P',
    () => void lookupNowPlaying(),
    'media',
  );

  // Clipboard history panel (fixed; not settings-editable)
  try {
    globalShortcut.unregister('CommandOrControl+Shift+V');
  } catch {
    /* ignore */
  }
  try {
    globalShortcut.register('CommandOrControl+Shift+V', () => {
      if (mainWindow) {
        mainWindow.webContents.send('show-clipboard-history');
      }
    });
  } catch {
    /* ignore */
  }
}

function registerFixedAppShortcuts(): void {
  syncFixedAppShortcuts();
}

function setHoverEnabled(enabled: boolean): void {
  monitorSettings = mergeMonitorSettings({ hoverEnabled: enabled }, monitorSettings);
  saveMonitorSettingsFile(monitorSettings);
  applyHoverFromSettings();
  updateTrayContextMenu();
  log.info('main', enabled ? 'Hover lookup enabled' : 'Hover lookup disabled');
  try {
    if (tray && !tray.isDestroyed()) {
      tray.displayBalloon?.({
        title: 'Phevere',
        content: enabled
          ? `Hover lookup on (${monitorSettings.hoverShortcut})`
          : `Hover lookup off (${monitorSettings.hoverShortcut})`,
      });
    }
  } catch {
    /* balloon optional */
  }
}

function applyHoverFromSettings(): void {
  const hover = ensureHoverLookup();
  if (monitorSettings.hoverEnabled) {
    if (!hover.isRunning()) hover.start();
  } else if (hover.isRunning()) {
    hover.stop();
  }
}

function tryRegisterAccelerator(accelerator: string): boolean {
  if (!accelerator || !accelerator.trim()) {
    return false;
  }
  // If it's already the currently registered accelerator, it's valid by default
  if (
    accelerator === registeredCycleAccelerator ||
    accelerator === registeredTriggerAccelerator ||
    accelerator === registeredOcrAccelerator ||
    accelerator === registeredHoverAccelerator ||
    accelerator === registeredGrabAccelerator ||
    accelerator === registeredReadWindowAccelerator ||
    accelerator === registeredClipboardOcrAccelerator ||
    accelerator === registeredMediaAccelerator
  ) {
    return true;
  }
  try {
    const ok = globalShortcut.register(accelerator, () => {});
    if (ok) {
      globalShortcut.unregister(accelerator);
    }
    return ok;
  } catch {
    return false;
  }
}

function applyMonitoringFromMode(): void {
  if (monitorSettings.mode === 'off') {
    void stopSelectionMonitoring();
  } else {
    startSelectionMonitoring();
  }
}

/** Resolve tray/window icon — __dirname can differ when webpack moves the main bundle. */
function resolveTrayIconPath(): string {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'tray-icon.png');
  }
  const candidates = [
    path.join(__dirname, '../../resources/tray-icon.png'),
    path.join(app.getAppPath(), 'resources', 'tray-icon.png'),
    path.join(process.cwd(), 'resources', 'tray-icon.png'),
  ];
  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        return p;
      }
    } catch {
      /* ignore */
    }
  }
  return candidates[0];
}

function getTrayIconPath(): string {
  return resolveTrayIconPath();
}

/** Same asset as tray — used for taskbar / window chrome (not the Electron default). */
function loadWindowIcon(): Electron.NativeImage | undefined {
  try {
    const p = resolveTrayIconPath();
    if (!fs.existsSync(p)) {
      log.warn('main', 'App icon file missing', { p });
      return undefined;
    }
    const img = nativeImage.createFromPath(p);
    if (!img.isEmpty()) {
      return img;
    }
    log.warn('main', 'App icon image empty', { p });
  } catch (e) {
    log.warn('main', 'App icon load failed', { err: String(e) });
  }
  return undefined;
}

function withPopupDevFlag(entryUrl: string): string {
  const sep = entryUrl.includes('?') ? '&' : '?';
  return `${entryUrl}${sep}phevere_dev=${app.isPackaged ? '0' : '1'}`;
}

function showOrRestoreMainWindow(): void {
  if (!mainWindow || mainWindow.isDestroyed()) {
    createMainWindow();
    return;
  }
  try {
    if (process.platform === 'win32' || process.platform === 'linux') {
      mainWindow.setSkipTaskbar(false);
    }
  } catch {
    /* ignore */
  }
  if (!mainWindow.isVisible()) {
    mainWindow.show();
  }
  mainWindow.focus();
}

/** Hide a window to tray (main window only — uses concrete BrowserWindow from IPC sender when global ref is stale). */
function hideMainToTray(target: BrowserWindow): void {
  if (!target || target.isDestroyed()) {
    return;
  }
  try {
    if (process.platform === 'win32' || process.platform === 'linux') {
      target.setSkipTaskbar(true);
    }
  } catch {
    /* ignore */
  }
  target.hide();
}

function buildTrayContextMenu(): Electron.Menu {
  return Menu.buildFromTemplate([
    {
      label: 'Open Phevere',
      click: () => showOrRestoreMainWindow(),
    },
    {
      label: 'Settings…',
      click: () => {
        showOrRestoreMainWindow();
        createSettingsWindow();
      },
    },
    { type: 'separator' },
    {
      label: 'Selection monitor',
      submenu: [
        {
          label: 'Off',
          type: 'radio',
          checked: monitorSettings.mode === 'off',
          click: () => setMonitoringMode('off'),
        },
        {
          label: 'On',
          type: 'radio',
          checked: monitorSettings.mode === 'on',
          click: () => setMonitoringMode('on'),
        },
        {
          label: 'Shortcut (hold trigger while selecting)',
          type: 'radio',
          checked: monitorSettings.mode === 'shortcut',
          click: () => setMonitoringMode('shortcut'),
        },
      ],
    },
    {
      label: 'Hover lookup',
      type: 'checkbox',
      checked: !!monitorSettings.hoverEnabled,
      accelerator: monitorSettings.hoverShortcut,
      click: (item) => setHoverEnabled(!!item.checked),
    },
    {
      label: 'OCR region…',
      accelerator: monitorSettings.ocrShortcut,
      click: () => {
        if (ocrOverlayWindow && !ocrOverlayWindow.isDestroyed()) {
          closeOcrOverlay();
        } else {
          void startOcrRegionCapture();
        }
      },
    },
    {
      label: 'Grab under cursor',
      accelerator: 'CommandOrControl+Shift+G',
      click: () => void grabOcrUnderCursor(),
    },
    {
      label: 'Read this window',
      accelerator: 'CommandOrControl+Shift+W',
      click: () => void readForegroundWindowOcr(),
    },
    {
      label: 'OCR clipboard image',
      accelerator: 'CommandOrControl+Shift+I',
      click: () => void ocrClipboardImage(),
    },
    {
      label: 'Now playing…',
      accelerator: 'CommandOrControl+Shift+P',
      click: () => void lookupNowPlaying(),
    },
    {
      label: 'Clipboard history',
      accelerator: 'CommandOrControl+Shift+V',
      click: () => {
        showOrRestoreMainWindow();
        try {
          mainWindow?.webContents.send('show-clipboard-history');
        } catch {
          /* ignore */
        }
      },
    },
    { type: 'separator' },
    {
      label: 'Quit Phevere',
      click: () => {
        /* Exits the Electron app. When using `electron-forge start`, the terminal may keep running until Ctrl+C (webpack dev server). */
        appIsQuitting = true;
        popupWindows.forEach((win) => {
          if (win && !win.isDestroyed()) win.close();
        });
        popupWindows = [];
        if (settingsWindow && !settingsWindow.isDestroyed()) {
          settingsWindow.close();
        }
        externalWindows.forEach((win) => {
          if (win && !win.isDestroyed()) win.close();
        });
        externalWindows = [];
        if (tray && !tray.isDestroyed()) {
          tray.destroy();
          tray = null;
        }
        if (mainWindow && !mainWindow.isDestroyed()) {
          mainWindow.destroy();
        }
        app.quit();
      },
    },
  ]);
}

function updateTrayContextMenu(): void {
  if (tray && !tray.isDestroyed()) {
    tray.setContextMenu(buildTrayContextMenu());
  }
}

/** 1×1 PNG fallback so Tray never receives an empty image on Windows. */
const TRAY_FALLBACK_PNG =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

function createTray(): void {
  if (tray && !tray.isDestroyed()) {
    return;
  }
  let image: Electron.NativeImage;
  try {
    image = nativeImage.createFromPath(getTrayIconPath());
    if (image.isEmpty()) {
      throw new Error('tray image empty');
    }
  } catch {
    try {
      image = nativeImage.createFromDataURL(`data:image/png;base64,${TRAY_FALLBACK_PNG}`);
    } catch {
      image = nativeImage.createEmpty();
    }
  }
  // Downscale large assets so the tray uses most of the glyph (avoids tiny centered artwork).
  if (!image.isEmpty()) {
    const { width, height } = image.getSize();
    const targetPx = process.platform === 'darwin' ? 44 : 32;
    if (width > targetPx || height > targetPx) {
      image = image.resize({ width: targetPx, height: targetPx, quality: 'best' });
    }
  }
  tray = new Tray(image);
  tray.setToolTip('Phevere — dictionary & selection');
  tray.setContextMenu(buildTrayContextMenu());
  tray.on('click', () => {
    showOrRestoreMainWindow();
  });
}

// Open custom wiki window in standalone web window (not inside dictionary popup)
ipcMain.on('open-wiki', (_e, term: string) => {
  try {
    if (!term || typeof term !== 'string' || term.trim().length === 0) {
      log.warn('main', 'Invalid Wikipedia term', { term: String(term) });
      return;
    }

    const cleanTerm = term.trim();
    const url = `https://en.wikipedia.org/wiki/${encodeURIComponent(cleanTerm)}`;
    log.info('main', 'Open Wikipedia', { term: cleanTerm });
    createWebWindow(url);
  } catch (error) {
    log.error('main', 'Error opening Wikipedia', { err: String(error) });
  }
});

const createMainWindow = (): void => {
  const windowIcon = loadWindowIcon();
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false,
    ...(windowIcon ? { icon: windowIcon } : {}),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      // Allow text selection and copying in the main window
      webSecurity: true,
    },
    show: false, // Don't show main window by default
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Show window when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  mainWindow.on('close', (event) => {
    if (!appIsQuitting) {
      event.preventDefault();
      if (mainWindow && !mainWindow.isDestroyed()) {
        hideMainToTray(mainWindow);
      }
    }
  });

  // REMOVED: This is dangerous and bypasses proper cleanup.
  // The 'window-all-closed' event handles this correctly.
  // mainWindow.on('closed', () => {
  //   console.log('[DEBUG] Main window closed, quitting app...');
  //   setTimeout(() => {
  //     console.log('[DEBUG] Force quitting app...');
  //     app.exit(0);
  //   }, 100);
  // });

  
};

const createPopupWindow = (x: number, y: number): void => {
  log.debug('main', 'Create popup window', { x, y });

  // Slim strip: width matches 8×24px icons + gaps + padding (keep in sync with popup-new.html strip resize)
  const POPUP_STRIP_ICON = 24;
  const POPUP_STRIP_GAP = 2;
  const POPUP_STRIP_PAD = 4;
  const POPUP_STRIP_ICONS = 8;
  const popupWidth =
    POPUP_STRIP_PAD +
    POPUP_STRIP_ICONS * POPUP_STRIP_ICON +
    (POPUP_STRIP_ICONS - 1) * POPUP_STRIP_GAP;
  const popupHeight = 34; // toolbar ~26px + small frame margin

  // Multi-monitor safe: physical → DIP via screenToDipPoint, clamp to nearest workArea
  // (never primary.workAreaSize — that pinned secondary-monitor selections to the left screen).
  const placed = placePopupNearPoint(x, y, popupWidth, popupHeight);
  const popupX = placed.x;
  const popupY = placed.y;
  log.debug('main', 'Popup bounds', { popupX, popupY, popupWidth, popupHeight, displayId: placed.displayId });

  // Coalesce duplicate requests for the same text within a short period
  const textForPopup = (lastSelectionEvent && (lastSelectionEvent.text || '').trim()) || lastSelectedText || '';
  const nowTs = Date.now();
  if (textForPopup && lastPopupText === textForPopup && (nowTs - lastPopupAt) < 1000) {
    log.debug('main', 'Skip duplicate popup (same text, 1s)');
    return;
  }

  // Additional check: prevent rapid successive popups regardless of text
  if (lastPopupAt && (nowTs - lastPopupAt) < 300) {
    log.debug('main', 'Skip rapid popup (300ms cooldown)');
    return;
  }

  // Commit immediately — do not wait for did-finish-load. Otherwise shortcut mode can
  // double-open: selection (keys held) + global trigger fire almost together, both pass
  // cooldown because lastPopupAt was still unset from the async popup path.
  lastPopupAt = nowTs;
  lastPopupText = textForPopup;

  // If a popup already exists, reuse it by moving and updating content (but do not resize here)
  const existing = popupWindows.find(win => win && !win.isDestroyed());
  if (existing) {
    try {
      // Only move; size will be managed by renderer's one-time request
      const [currW, currH] = existing.getSize();
      existing.setBounds({ x: popupX, y: popupY, width: currW, height: currH }, false);
      existing.show();
      try { existing.focus(); } catch {}
      if (textForPopup) existing.webContents.send('popup-text', textForPopup);
      log.debug('main', 'Reuse existing popup');
      return;
    } catch (e) {
      log.warn('main', 'Popup reuse failed, creating new', { err: String(e) });
    }
  }

                const newPopupWindow = new BrowserWindow({
                width: popupWidth,
                height: popupHeight,
                x: popupX,
                y: popupY,
                frame: false,
                resizable: true,
                alwaysOnTop: true,
                skipTaskbar: true, // Hide from taskbar as requested
                focusable: true,
                show: false,
                transparent: false,
                minWidth: 160,
                minHeight: 28,
                maxWidth: 1200,
                maxHeight: 900,
                movable: true, // Make window draggable
                webPreferences: {
                  preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
                  nodeIntegration: false,
                  contextIsolation: true,
                },
              });
  // Close on blur to match intended UX
  newPopupWindow.on('blur', () => {
    // Use a shorter timeout to be more responsive, but still allow for focus transitions
    setTimeout(() => {
      try {
        if (newPopupWindow.isDestroyed()) return;

        const focused = BrowserWindow.getFocusedWindow();
        const isPopupFocused = focused === newPopupWindow;

        // Only close if popup is not focused and no other app windows are focused
        // This prevents closing when user clicks between app windows
        if (!isPopupFocused && (!focused || !popupWindows.includes(focused))) {
          log.debug('main', 'Close popup on blur');
          newPopupWindow.close();
        } else {
          log.debug('main', 'Keep popup (focus)');
        }
      } catch (e) {
        log.warn('main', 'Popup blur check failed', { err: String(e) });
      }
    }, 150); // Reduced from 250ms to be more responsive
  });
// (moved) wiki handler registered at top-level below

  // Add error handling for load failures
  newPopupWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL) => {
    log.error('main', 'Popup load failed', { errorCode, errorDescription, validatedURL });
  });

  // FIXED: Load the correct HTML file for the new popup using webpack entry point
  // Load the dedicated popup bundle (popup-new.html) without #popup so its own DOM is used
  const popupUrl = withPopupDevFlag(POPUP_WINDOW_WEBPACK_ENTRY);
  newPopupWindow.loadURL(popupUrl).catch((error) => {
    log.error('main', 'Popup loadURL failed', { err: String(error) });
  });

  // After the popup finishes loading, send the selected text to the renderer
  newPopupWindow.webContents.on('did-finish-load', () => {
    try {
      const textToSend = (lastSelectionEvent && lastSelectionEvent.text) || lastSelectedText || '';
      if (textToSend) {
        newPopupWindow.webContents.send('popup-text', textToSend);
      }
      lastPopupText = textToSend;
    } catch (e) {
      log.warn('main', 'Send popup-text failed', { err: String(e) });
    }
  });

  // Show popup when ready
  newPopupWindow.once('ready-to-show', () => {
    newPopupWindow.show();
    try { newPopupWindow.focus(); } catch {}
  });

                newPopupWindow.on('closed', () => {
                popupWindows = popupWindows.filter(win => win !== newPopupWindow);

                // Reset selection state to allow same word to trigger popup again
                lastSelectionEvent = null; // Reset the main process selection state
                lastSelectedText = ''; // Reset the last selected text
              });

  popupWindows.push(newPopupWindow);
};

const createSettingsWindow = (): void => {
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    settingsWindow.focus();
    return;
  }

  settingsWindow = new BrowserWindow({
    width: 760,
    height: 780,
    parent: mainWindow || undefined,
    modal: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
    show: false,
    frame: false,
  });

  const settingsUrl = MAIN_WINDOW_WEBPACK_ENTRY + '#settings';
  settingsWindow.loadURL(settingsUrl);

  settingsWindow.once('ready-to-show', () => {
    settingsWindow?.show();
  });

  settingsWindow.on('closed', () => {
    settingsWindow = null;
  });
  // Allow ESC to close via IPC from renderer
  settingsWindow.webContents.on('before-input-event', (_event, input) => {
    if (input.key === 'Escape') {
      settingsWindow?.close();
    }
  });
};

/**
 * Phase 0 fan-in: every ContextEvent (selection, OCR, …) goes through here.
 */
function wireContextCaptureHubOnce(): void {
  if (contextHubWired) {
    return;
  }
  contextHubWired = true;

  contextCaptureHub.onContext((event: ContextEvent) => {
    const focused = BrowserWindow.getFocusedWindow();
    if (
      focused &&
      (popupWindows.includes(focused) ||
        focused === mainWindow ||
        focused === settingsWindow ||
        focused === ocrOverlayWindow ||
        externalWindows.includes(focused))
    ) {
      // Explicit capture origins (OCR / clipboard / media / manual) may finish while Phevere is focused.
      if (
        event.origin !== 'ocr' &&
        event.origin !== 'clipboard' &&
        event.origin !== 'media' &&
        event.origin !== 'manual'
      ) {
        return;
      }
    }

    lastSelectionEvent = event;
    lastSelectedText = event.text || '';

    // Hover and OCR always open the popup when monitoring isn't off.
    // Classic drag-selection still respects shortcut-mode hold semantics.
    if (event.origin === 'selection' && monitorSettings.mode === 'shortcut') {
      try {
        mainWindow?.webContents.send('selection-changed', event.text);
      } catch (e) {
        log.warn('main', 'selection-changed IPC failed', { err: String(e) });
      }
      if (isAcceleratorPhysicallyHeld(monitorSettings.triggerShortcut)) {
        createPopupWindow(event.x, event.y);
      }
      return;
    }

    if (monitorSettings.mode === 'off' && event.origin === 'selection') {
      return;
    }

    // OCR / hover work even if the user only opened the overlay while mode was on;
    // region OCR shortcut is always registered regardless of monitor mode.
    if (monitorSettings.mode === 'off' && event.origin === 'hover') {
      return;
    }

    try {
      mainWindow?.webContents.send('selection-changed', event.text);
    } catch (e) {
      log.warn('main', 'selection-changed IPC failed', { err: String(e) });
    }
    createPopupWindow(event.x, event.y);
  });
}

function registerNativeSelectionHandlerOnce(): void {
  if (nativeSelectionHandlerRegistered) {
    return;
  }
  nativeSelectionHandlerRegistered = true;
  wireContextCaptureHubOnce();

  nativeSelectionService.onSelection((event: SelectionEvent) => {
    contextCaptureHub.emit({
      ...event,
      origin: event.origin || 'selection',
      source: event.source || 'native',
    } as SelectionEvent);
  });
}

function closeOcrOverlay(): void {
  if (ocrOverlayWindow && !ocrOverlayWindow.isDestroyed()) {
    ocrOverlayWindow.close();
  }
  ocrOverlayWindow = null;
}

async function startOcrRegionCapture(): Promise<void> {
  wireContextCaptureHubOnce();

  if (ocrOverlayWindow && !ocrOverlayWindow.isDestroyed()) {
    ocrOverlayWindow.focus();
    return;
  }

  const cursor = screen.getCursorScreenPoint();
  const display = screen.getDisplayNearestPoint(cursor);

  ocrOverlayWindow = new BrowserWindow({
    x: display.bounds.x,
    y: display.bounds.y,
    width: display.bounds.width,
    height: display.bounds.height,
    frame: false,
    transparent: true,
    resizable: false,
    movable: false,
    fullscreenable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    hasShadow: false,
    focusable: true,
    show: false,
    webPreferences: {
      preload: OCR_OVERLAY_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  ocrOverlayWindow.setAlwaysOnTop(true, 'screen-saver');
  ocrOverlayWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  ocrOverlayWindow.setIgnoreMouseEvents(false);

  ocrOverlayWindow.on('closed', () => {
    ocrOverlayWindow = null;
  });

  try {
    await ocrOverlayWindow.loadURL(OCR_OVERLAY_WEBPACK_ENTRY);
    ocrOverlayWindow.show();
    ocrOverlayWindow.focus();
    log.info('main', 'OCR region overlay opened');
  } catch (error) {
    log.error('main', 'Failed to open OCR overlay', { err: String(error) });
    closeOcrOverlay();
  }
}

async function handleOcrRegionSelected(region: {
  x: number;
  y: number;
  width: number;
  height: number;
}): Promise<void> {
  const overlayBounds = ocrOverlayWindow?.getBounds();
  closeOcrOverlay();

  // Overlay uses client/DIP coords relative to its window; map to screen DIP.
  const screenRegion = {
    x: Math.round((overlayBounds?.x || 0) + region.x),
    y: Math.round((overlayBounds?.y || 0) + region.y),
    width: Math.round(region.width),
    height: Math.round(region.height),
  };

  const progressX = screenRegion.x + Math.floor(screenRegion.width / 2);
  const progressY = screenRegion.y + screenRegion.height;

  log.info('main', 'OCR region selected', screenRegion);

  showWorkProgress(progressX, progressY, {
    title: 'Recognizing text…',
    subtitle: 'Capturing screen region',
  });

  const capture = await captureScreenRegion(screenRegion);
  if (!capture) {
    closeWorkProgress();
    log.warn('main', 'Screen capture failed for OCR region');
    return;
  }

  updateWorkProgress({
    title: 'Recognizing text…',
    subtitle: 'Running PP-OCRv6 (RapidOCR) — large regions can take several seconds',
  });

  const started = Date.now();
  const tick = setInterval(() => {
    const secs = Math.round((Date.now() - started) / 1000);
    updateWorkProgress({
      title: 'Recognizing text…',
      subtitle: `Still working… ${secs}s`,
    });
  }, 800);

  let ocr;
  try {
    ocr = await ocrEngine.recognize(capture.png);
  } finally {
    clearInterval(tick);
  }

  const text = (ocr.text || '').trim();

  if (!text || !isLookupWorthy(text)) {
    closeWorkProgress();
    log.warn('main', 'OCR produced no lookup-worthy text', {
      engine: ocr.engine,
      language: ocr.language,
      rawLen: (ocr.text || '').length,
    });
    const available = await ocrEngine.isAvailable().catch(() => false);
    contextCaptureHub.emit({
      text: available
        ? '(No text recognized in selection)'
        : '(OCR unavailable — RapidOCR/Python not found. Set PHEVERE_PYTHON to your python.exe)',
      x: progressX,
      y: progressY,
      timestamp: Date.now(),
      origin: 'ocr',
      confidence: 0,
      bounds: screenRegion,
      imageHash: capture.imageHash,
    });
    return;
  }

  updateWorkProgress({
    title: 'Looking up…',
    subtitle: text.length > 48 ? text.slice(0, 48) + '…' : text,
  });

  // Brief beat so the user sees the transition, then hand off to the popup.
  setTimeout(() => closeWorkProgress(), 180);

  contextCaptureHub.emit({
    text,
    x: progressX,
    y: progressY,
    timestamp: Date.now(),
    origin: 'ocr',
    confidence: ocr.confidence,
    bounds: screenRegion,
    imageHash: capture.imageHash,
  });
}

ipcMain.on('ocr-overlay-complete', (_event, region) => {
  void handleOcrRegionSelected(region);
});

ipcMain.on('ocr-overlay-cancel', () => {
  log.debug('main', 'OCR overlay cancelled');
  closeOcrOverlay();
});

async function emitOcrFromPng(opts: {
  png: Buffer;
  x: number;
  y: number;
  bounds?: { x: number; y: number; width: number; height: number };
  imageHash?: string;
  origin: ContextEvent['origin'];
  progressTitle?: string;
  emptyMessage?: string;
}): Promise<void> {
  wireContextCaptureHubOnce();
  showWorkProgress(opts.x, opts.y, {
    title: opts.progressTitle || 'Recognizing text…',
    subtitle: 'Running PP-OCRv6 (RapidOCR)',
  });

  const started = Date.now();
  const tick = setInterval(() => {
    const secs = Math.round((Date.now() - started) / 1000);
    updateWorkProgress({
      title: opts.progressTitle || 'Recognizing text…',
      subtitle: `Still working… ${secs}s`,
    });
  }, 800);

  let ocr;
  try {
    ocr = await ocrEngine.recognize(opts.png);
  } finally {
    clearInterval(tick);
  }

  const text = (ocr.text || '').trim();
  if (!text || !isLookupWorthy(text)) {
    closeWorkProgress();
    const available = await ocrEngine.isAvailable().catch(() => false);
    contextCaptureHub.emit({
      text:
        opts.emptyMessage ||
        (available
          ? '(No text recognized)'
          : '(OCR unavailable — RapidOCR/Python not found. Set PHEVERE_PYTHON)'),
      x: opts.x,
      y: opts.y,
      timestamp: Date.now(),
      origin: opts.origin,
      confidence: 0,
      bounds: opts.bounds,
      imageHash: opts.imageHash,
    });
    return;
  }

  updateWorkProgress({
    title: 'Looking up…',
    subtitle: text.length > 48 ? text.slice(0, 48) + '…' : text,
  });
  setTimeout(() => closeWorkProgress(), 180);

  contextCaptureHub.emit({
    text,
    x: opts.x,
    y: opts.y,
    timestamp: Date.now(),
    origin: opts.origin,
    confidence: ocr.confidence,
    bounds: opts.bounds,
    imageHash: opts.imageHash,
  });
}

async function grabOcrUnderCursor(): Promise<void> {
  const cur = screen.getCursorScreenPoint();
  log.info('main', 'Grab OCR under cursor', { x: cur.x, y: cur.y });
  showWorkProgress(cur.x, cur.y + 24, {
    title: 'Grab under cursor…',
    subtitle: 'Capturing nearby text',
  });
  const capture = await captureAroundPoint(cur.x, cur.y, 160, 64);
  if (!capture) {
    closeWorkProgress();
    log.warn('main', 'Grab capture failed');
    return;
  }
  await emitOcrFromPng({
    png: capture.png,
    x: cur.x,
    y: cur.y + 24,
    bounds: capture.bounds,
    imageHash: capture.imageHash,
    origin: 'ocr',
    progressTitle: 'Grab under cursor…',
  });
}

async function readForegroundWindowOcr(): Promise<void> {
  const bounds = getForegroundWindowBoundsDip();
  const cur = screen.getCursorScreenPoint();
  if (!bounds) {
    log.warn('main', 'Foreground window bounds unavailable');
    contextCaptureHub.emit({
      text: '(Could not read foreground window bounds)',
      x: cur.x,
      y: cur.y,
      timestamp: Date.now(),
      origin: 'ocr',
    });
    return;
  }

  // Avoid OCR of Phevere chrome when it is focused.
  if (phevereWindowFocused(mainWindow, popupWindows, settingsWindow, ocrOverlayWindow, externalWindows)) {
    log.info('main', 'Read-window skipped — Phevere focused');
    return;
  }

  log.info('main', 'Read foreground window OCR', { ...bounds });
  showWorkProgress(bounds.x + Math.floor(bounds.width / 2), bounds.y + 40, {
    title: 'Reading window…',
    subtitle: 'Capturing foreground window',
  });
  const capture = await captureScreenRegion(bounds);
  if (!capture) {
    closeWorkProgress();
    return;
  }
  await emitOcrFromPng({
    png: capture.png,
    x: bounds.x + Math.floor(bounds.width / 2),
    y: bounds.y + 40,
    bounds,
    imageHash: capture.imageHash,
    origin: 'ocr',
    progressTitle: 'Reading window…',
  });
}

async function ocrClipboardImage(): Promise<void> {
  const cur = screen.getCursorScreenPoint();
  const img = readClipboardImage();
  if (!img) {
    log.info('main', 'No clipboard image to OCR');
    try {
      tray?.displayBalloon?.({
        title: 'Phevere',
        content: 'No image on the clipboard (try Win+Shift+S first)',
      });
    } catch {
      /* optional */
    }
    return;
  }
  lastClipboardImageHash = img.imageHash;
  await emitOcrFromPng({
    png: img.png,
    x: cur.x,
    y: cur.y,
    imageHash: img.imageHash,
    origin: 'clipboard',
    progressTitle: 'OCR clipboard image…',
  });
}

async function lookupNowPlaying(): Promise<void> {
  wireContextCaptureHubOnce();
  const cur = screen.getCursorScreenPoint();
  showWorkProgress(cur.x, cur.y, {
    title: 'Now playing…',
    subtitle: 'Reading media session',
  });
  const info = await getNowPlaying();
  closeWorkProgress();
  if (!info) {
    contextCaptureHub.emit({
      text: '(No media session / now playing)',
      x: cur.x,
      y: cur.y,
      timestamp: Date.now(),
      origin: 'media',
    });
    return;
  }
  const query = formatNowPlayingQuery(info);
  contextCaptureHub.emit({
    text: query,
    x: cur.x,
    y: cur.y,
    timestamp: Date.now(),
    origin: 'media',
  });
}

function startClipboardImageWatcher(): void {
  if (clipboardImageWatchTimer) return;
  clipboardImageWatchTimer = setInterval(() => {
    const img = readClipboardImage();
    if (!img) return;
    if (img.imageHash === lastClipboardImageHash) return;
    lastClipboardImageHash = img.imageHash;
    try {
      tray?.displayBalloon?.({
        title: 'Phevere',
        content: 'Clipboard image ready — Ctrl+Shift+I to OCR',
      });
    } catch {
      /* optional */
    }
  }, 2000);
}

ipcMain.handle('ocr-image-file', async (_event, filePath: string) => {
  const cur = screen.getCursorScreenPoint();
  const img = loadImageFileAsPng(String(filePath || ''));
  if (!img) return { success: false, error: 'Could not load image' };
  await emitOcrFromPng({
    png: img.png,
    x: cur.x,
    y: cur.y,
    imageHash: img.imageHash,
    origin: 'ocr',
    progressTitle: 'OCR dropped image…',
  });
  return { success: true };
});

ipcMain.handle('ocr-image-data', async (_event, dataUrl: string) => {
  const cur = screen.getCursorScreenPoint();
  const img = pngFromBase64(String(dataUrl || ''));
  if (!img) return { success: false, error: 'Could not decode image' };
  await emitOcrFromPng({
    png: img.png,
    x: cur.x,
    y: cur.y,
    imageHash: img.imageHash,
    origin: 'clipboard',
    progressTitle: 'OCR pasted image…',
  });
  return { success: true };
});

function ensureHoverLookup(): HoverLookupService {
  if (!hoverLookup) {
    hoverLookup = new HoverLookupService({
      getWordAtPoint: (x, y) => {
        if (typeof nativeSelectionService.getWordAtPoint === 'function') {
          return nativeSelectionService.getWordAtPoint(x, y);
        }
        return { text: '', x, y };
      },
      isBlocked: () =>
        phevereWindowFocused(mainWindow, popupWindows, settingsWindow, ocrOverlayWindow, externalWindows),
    });
  }
  return hoverLookup;
}

function startSelectionMonitoring(): void {
  log.debug('main', 'Start native selection monitoring');

  if (nativeSelectionActive) {
    return;
  }

  const isAdmin = checkAdminPrivileges();

  if (!isAdmin) {
    log.warn('main', 'Not running as administrator; UIAutomation may be limited');
  }

  nativeSelectionActive = true;

  try {
    registerNativeSelectionHandlerOnce();

    nativeSelectionService
      .start()
      .then(() => {
        log.info('main', 'Native selection service started');
        updateTrayContextMenu();
      })
      .catch((error) => {
        nativeSelectionActive = false;
        log.error('main', 'Failed to start native selection', { err: String(error) });
        if (!isAdmin) {
          log.error('main', 'Try running as Administrator for UIAutomation');
        }
        updateTrayContextMenu();
      });
  } catch (error: any) {
    log.error('main', 'Start selection monitoring failed', { err: String(error), stack: error?.stack });
    nativeSelectionActive = false;
  }
}

async function stopSelectionMonitoring(): Promise<void> {
  if (!nativeSelectionActive) {
    return;
  }

  try {
    nativeSelectionActive = false;
    log.debug('main', 'Stopping selection monitoring');

    await nativeSelectionService.stop();
    log.info('main', 'Native selection service stopped');
  } catch (error) {
    log.error('main', 'Stop selection monitoring failed', { err: String(error) });
  }
  updateTrayContextMenu();
}

// IPC handlers
ipcMain.handle('start-monitoring', () => {
  setMonitoringMode('on');
  return { success: true };
});

// Manual test for text selection
ipcMain.handle('test-text-selection', () => {
  log.debug('main', 'Manual text selection test');
  
  // Reset last selected text to allow testing same text
  lastSelectedText = '';
  
  // Simulate a text selection
  const testText = 'hello world';
  
  // Get cursor position
  const cursorPosition = screen.getCursorScreenPoint();
  log.debug('main', 'Test selection cursor', { x: cursorPosition.x, y: cursorPosition.y });
  
  // Create popup with test text
  createPopupWindow(cursorPosition.x, cursorPosition.y);
  try { mainWindow?.webContents.send('selection-changed', testText); } catch {}
  
  return { success: true, text: testText };
});

// Reset selection state for testing
ipcMain.handle('reset-selection-state', () => {
  log.debug('main', 'Reset selection state');
  lastSelectedText = '';
  return { success: true };
});

ipcMain.handle('stop-monitoring', () => {
  setMonitoringMode('off');
  return { success: true };
});

ipcMain.handle('monitor-get-state', () => {
  return {
    mode: monitorSettings.mode,
    cycleShortcut: monitorSettings.cycleShortcut,
    triggerShortcut: monitorSettings.triggerShortcut,
    hoverEnabled: monitorSettings.hoverEnabled,
    ocrShortcut: monitorSettings.ocrShortcut,
    hoverShortcut: monitorSettings.hoverShortcut,
  };
});

ipcMain.handle('monitor-set-mode', (_event, mode: MonitorMode) => {
  if (mode !== 'off' && mode !== 'on' && mode !== 'shortcut') {
    return { success: false, error: 'Invalid mode' };
  }
  setMonitoringMode(mode);
  return { success: true };
});

ipcMain.handle('monitor-cycle-mode', () => {
  cycleMonitoringMode();
  return { success: true, mode: monitorSettings.mode };
});

ipcMain.handle(
  'monitor-set-shortcuts',
  (
    _event,
    payload: {
      cycleShortcut: string;
      triggerShortcut: string;
      ocrShortcut?: string;
      hoverShortcut?: string;
      hoverEnabled?: boolean;
    },
  ) => {
    const cycle = (payload?.cycleShortcut || '').trim();
    const trigger = (payload?.triggerShortcut || '').trim();
    const ocr = (payload?.ocrShortcut || monitorSettings.ocrShortcut).trim();
    const hover = (payload?.hoverShortcut || monitorSettings.hoverShortcut).trim();
    if (!cycle || !trigger || !ocr || !hover) {
      return { success: false, error: 'All shortcut fields are required.' };
    }
    const all = [cycle, trigger, ocr, hover];
    if (new Set(all).size !== all.length) {
      return { success: false, error: 'Shortcuts must all be unique.' };
    }
    if (
      !tryRegisterAccelerator(cycle) ||
      !tryRegisterAccelerator(trigger) ||
      !tryRegisterAccelerator(ocr) ||
      !tryRegisterAccelerator(hover)
    ) {
      return {
        success: false,
        error: 'Invalid accelerator. Use Electron format, e.g. CommandOrControl+Shift+O',
      };
    }
    monitorSettings = mergeMonitorSettings(
      {
        cycleShortcut: cycle,
        triggerShortcut: trigger,
        ocrShortcut: ocr,
        hoverShortcut: hover,
        hoverEnabled:
          typeof payload?.hoverEnabled === 'boolean' ? payload.hoverEnabled : monitorSettings.hoverEnabled,
      },
      monitorSettings,
    );
    saveMonitorSettingsFile(monitorSettings);
    syncGlobalMonitorShortcuts();
    syncFixedAppShortcuts();
    applyHoverFromSettings();
    updateTrayContextMenu();
    return { success: true };
  },
);

ipcMain.on('show-popup', (event, { x, y, text }) => {
  lastSelectionEvent = selectionToContext(text, x, y, 'manual');
  createPopupWindow(x, y);
});

ipcMain.on('hide-popup', () => {
  popupWindows.forEach(win => {
    if (win && !win.isDestroyed()) {
      win.close();
    }
  });
  popupWindows = [];
});

ipcMain.handle('show-settings-window', () => {
  createSettingsWindow();
});

// Clipboard service IPC handlers
ipcMain.handle('clipboard-start-monitoring', () => {
  clipboardService.startMonitoring();
  return { success: true };
});

ipcMain.handle('clipboard-stop-monitoring', () => {
  clipboardService.stopMonitoring();
  return { success: true };
});

ipcMain.handle('clipboard-get-history', () => {
  clipboardService.syncFromClipboard();
  return clipboardService.getHistory();
});

ipcMain.handle('clipboard-get-recent', (event, count: number = 10) => {
  return clipboardService.getRecentEntries(count);
});

ipcMain.handle('clipboard-search', (event, query: string) => {
  return clipboardService.searchHistory(query);
});

ipcMain.handle('clipboard-copy', (event, text: string) => {
  clipboardService.copyToClipboard(text);
  return { success: true };
});

ipcMain.handle('clipboard-clear', () => {
  clipboardService.clearHistory();
  return { success: true };
});

ipcMain.handle('clipboard-remove-entry', (event, id: string) => {
  return clipboardService.removeEntry(id);
});

ipcMain.handle('clipboard-get-stats', () => {
  return clipboardService.getStats();
});

ipcMain.handle('clipboard-export', () => {
  return clipboardService.exportHistory();
});

ipcMain.handle('clipboard-import', (event, jsonData: string) => {
  return clipboardService.importHistory(jsonData);
});

// Dictionary service IPC handlers
ipcMain.handle('dictionary-lookup', async (event, text: string, targetLanguage: string = 'auto', enabledSources?: string[]) => {
  try {
    const result = await dictionaryService.lookup(text, targetLanguage, enabledSources);
    log.debug('main', 'Dictionary lookup OK', { wordLen: (text || '').length });
    return result;
  } catch (error) {
    log.error('main', 'Dictionary lookup failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('dictionary-set-api-key', (event, apiKey: string) => {
  dictionaryService.setApiKey(apiKey);
  return { success: true };
});

ipcMain.handle('dictionary-set-deepl-api-key', (event, deeplApiKey: string) => {
  dictionaryService.setDeepLApiKey(deeplApiKey);
  return { success: true };
});

// Premium dictionary credential handlers
ipcMain.handle('dictionary-set-oxford-credentials', (_event, appId: string, appKey: string) => {
  dictionaryService.setOxfordCredentials(appId, appKey);
  return { success: true };
});

ipcMain.handle('dictionary-set-youdao-credentials', (_event, appKey: string, appSecret: string) => {
  dictionaryService.setYoudaoCredentials(appKey, appSecret);
  return { success: true };
});

ipcMain.handle('dictionary-set-wordsapi-credentials', (_event, rapidApiKey: string, rapidApiHost?: string) => {
  dictionaryService.setWordsApiCredentials(rapidApiKey, rapidApiHost);
  return { success: true };
});

ipcMain.handle('dictionary-set-collins-credentials', (_event, rapidApiKey: string, rapidApiHost: string) => {
  dictionaryService.setCollinsApiCredentials(rapidApiKey, rapidApiHost);
  return { success: true };
});

ipcMain.handle('dictionary-load-cc-cedict', async (_event, url: string) => {
  const ok = await dictionaryService.loadCcCedictFromUrl(url);
  return { success: ok };
});

ipcMain.handle('dictionary-get-sources', () => {
  return dictionaryService.getAvailableSources();
});

ipcMain.handle('dictionary-get-source-stats', () => {
  return dictionaryService.getSourceStats();
});

ipcMain.handle('dictionary-clear-cache', () => {
  dictionaryService.clearCache();
  return { success: true };
});

ipcMain.handle('dictionary-get-cache-stats', () => {
  return dictionaryService.getCacheStats();
});

// Provide a cache-first recall for history lookups
ipcMain.handle('dictionary-recall', async (_event, text: string, targetLanguage: string = 'en') => {
  try {
    // First try cache
    const key = `${(text || '').toLowerCase()}_${targetLanguage}`;
    const stats = dictionaryService.getCacheStats();
    if (stats.entries.includes(key)) {
      // reuse existing regular lookup, which will return cache immediately
      return await dictionaryService.lookup(text, targetLanguage);
    }
    // If not cached, do a normal lookup (it will cache)
    return await dictionaryService.lookup(text, targetLanguage);
  } catch (e) {
    log.error('main', 'Dictionary recall failed', { err: String(e) });
    throw e;
  }
});

ipcMain.handle('dictionary-get-enabled-sources', () => {
  const list = dictionaryService.getEnabledSources();
  log.debug('main', 'getEnabledSources', { count: list.length });
  return list;
});

ipcMain.handle('dictionary-set-source-enabled', (event, sourceName: string, enabled: boolean) => {
  log.debug('main', 'setSourceEnabled', { sourceName, enabled });
  dictionaryService.setSourceEnabled(sourceName, enabled);
  return { success: true };
});

ipcMain.handle('dictionary-get-supported-languages', () => {
  return dictionaryService.getSupportedLanguages();
});

// Wikipedia service IPC handlers
ipcMain.handle('wikipedia-search', async (event, term: string, language: string = 'en', limit: number = 5) => {
  try {
    return await wikipediaService.search(term, language, limit);
  } catch (error) {
    log.error('main', 'Wikipedia search failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('wikipedia-get-random', async (event, language: string = 'en') => {
  try {
    return await wikipediaService.getRandomArticle(language);
  } catch (error) {
    log.error('main', 'Wikipedia random failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('wikipedia-get-categories', async (event, pageId: number, language: string = 'en') => {
  try {
    return await wikipediaService.getCategories(pageId, language);
  } catch (error) {
    log.error('main', 'Wikipedia categories failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('wikipedia-get-related', async (event, pageId: number, language: string = 'en', limit: number = 5) => {
  try {
    return await wikipediaService.getRelatedArticles(pageId, language, limit);
  } catch (error) {
    log.error('main', 'Wikipedia related failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('wikipedia-clear-cache', () => {
  wikipediaService.clearCache();
  return { success: true };
});

ipcMain.handle('wikipedia-get-cache-stats', () => {
  return wikipediaService.getCacheStats();
});

// Search service IPC handlers
ipcMain.handle('get-last-selection', () => {
  return lastSelectionEvent;
});

ipcMain.handle('search-get-suggestions', async (event, query: string) => {
  try {
    return await searchService.getSuggestions(query);
  } catch (error) {
    log.error('main', 'Search suggestions failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('search-query', async (event, query: string, limit: number = 5) => {
  try {
    return await searchService.search(query, limit);
  } catch (error) {
    log.error('main', 'Search query failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('search-get-related', async (event, query: string) => {
  try {
    return await searchService.getRelatedSearches(query);
  } catch (error) {
    log.error('main', 'Related searches failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('search-get-trending', async () => {
  try {
    return await searchService.getTrendingSearches();
  } catch (error) {
    log.error('main', 'Trending searches failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('search-get-stats', async (event, query: string) => {
  try {
    return await searchService.getSearchStats(query);
  } catch (error) {
    log.error('main', 'Search stats failed', { err: String(error) });
    throw error;
  }
});

ipcMain.handle('search-clear-cache', () => {
  searchService.clearCache();
  return { success: true };
});

ipcMain.handle('search-get-cache-stats', () => {
  return searchService.getCacheStats();
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  if (process.platform === 'win32') {
    app.setAppUserModelId('com.phevere.dictionary');
  }
  log.info('main', 'App ready');
  monitorSettings = loadMonitorSettings();
  createMainWindow();
  createTray();
  registerFixedAppShortcuts();
  startClipboardImageWatcher();
  syncGlobalMonitorShortcuts();
  applyMonitoringFromMode();
  applyHoverFromSettings();
  clipboardService.startMonitoring();
  // Warm RapidOCR models in the background so Ctrl+Shift+O is responsive.
  void ocrEngine
    .isAvailable()
    .then((ok) => {
      if (ok && ocrEngine.warmUp) return ocrEngine.warmUp();
    })
    .catch((err) => log.warn('main', 'OCR warm-up skipped', { err: String(err) }));
  log.info('main', 'Initialization complete');
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (!appIsQuitting) {
    // Main window is hidden (not destroyed); popups may close independently — stay in tray.
    return;
  }

  popupWindows.forEach((win) => {
    if (win && !win.isDestroyed()) {
      win.close();
    }
  });
  popupWindows = [];

  externalWindows.forEach((win) => {
    if (win && !win.isDestroyed()) {
      win.close();
    }
  });
  externalWindows = [];

  stopSelectionMonitoring();
  clipboardService.stopMonitoring();
  globalShortcut.unregisterAll();

  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createMainWindow();
  } else {
    showOrRestoreMainWindow();
  }
});

// Cleanup on app quit
ipcMain.on('open-external', (_event, url: string) => {
  try {
    log.debug('main', 'Open external', { host: new URL(url).hostname });
  } catch {
    log.debug('main', 'Open external');
  }
  shell.openExternal(url);
});

// Open URL inside Electron instead of external browser (user-toggle can call this)
ipcMain.on('open-in-app', (_event, url: string) => {
  createWebWindow(url);
});

// Open full dictionary window in-app for a given term
ipcMain.on('open-full-lookup', (_event, term: string) => {
  try {
    createDictionaryWindow(term);
  } catch (e) {
    log.error('main', 'Open full lookup failed', { err: String(e) });
  }
});

// New popup functionality handlers
ipcMain.on('search-wikipedia', (event, term: string) => {
  // Route to in-app web window or later embed panel; keep simple redirect working
  const url = `https://en.wikipedia.org/wiki/${encodeURIComponent(term)}`;
  createWebWindow(url);
});

            ipcMain.on('search-web', (event, term: string) => {
              log.debug('main', 'Search web', { termLen: (term || '').length });
              const url = `https://www.google.com/search?q=${encodeURIComponent(term)}`;
              createWebWindow(url);
            });

            ipcMain.on('window-resize', (event, { width, height }) => {
              log.debug('main', 'Popup resize', { width, height });
              const popupWindow = popupWindows.find(win => win && !win.isDestroyed());
              if (popupWindow) {
                popupWindow.setSize(width, height);
              }
            });

            ipcMain.on('open-clipboard', () => {
              log.debug('main', 'Open clipboard window');
              // Create a clipboard history window
              const clipboardWindow = new BrowserWindow({
                width: 500,
                height: 600,
                frame: false,
                resizable: true,
                alwaysOnTop: true,
                webPreferences: {
                  preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
                  nodeIntegration: false,
                  contextIsolation: true,
                },
              });

              clipboardWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY + '#clipboard');

              clipboardWindow.on('closed', () => {
                log.debug('main', 'Clipboard window closed');
              });
            });

            ipcMain.on('show-settings', () => {
              log.debug('main', 'Open settings');
              createSettingsWindow();
            });

            ipcMain.on('create-new-popup', (event, text: string) => {
              log.debug('main', 'Create new popup', { textLen: text.length });
              // Get current mouse position for new popup
              const mousePosition = screen.getCursorScreenPoint();
              // Set last selection so popup can render the word immediately
              lastSelectionEvent = selectionToContext(text, mousePosition.x, mousePosition.y, 'manual');
              // Also broadcast to recent selections UI
              try { mainWindow?.webContents.send('selection-changed', text); } catch {}
              createPopupWindow(mousePosition.x, mousePosition.y);
            });

// Window control handlers
ipcMain.on('window-minimize', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.minimize();
  }
});

ipcMain.on('window-maximize', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow.maximize();
    }
  }
});

ipcMain.handle('window-hide-to-tray', (event) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (!win || win.isDestroyed()) {
    return { ok: false as const };
  }
  if (mainWindow && win.id !== mainWindow.id) {
    win.close();
    return { ok: true as const };
  }
  hideMainToTray(win);
  return { ok: true as const };
});

app.on('before-quit', () => {
  appIsQuitting = true;
});

app.on('will-quit', () => {
  log.info('main', 'Will quit');
  void stopSelectionMonitoring();
  hoverLookup?.stop();
  closeWorkProgress();
  clipboardService.stopMonitoring();
  ocrEngine.dispose?.();
  globalShortcut.unregisterAll();
  if (tray && !tray.isDestroyed()) {
    tray.destroy();
    tray = null;
  }
});

app.on('quit', () => {
  log.info('main', 'Quit');
});

// Function to open a URL in a new window
const openWebWindows: { [url: string]: BrowserWindow | null } = {};

function createWebWindow(url: string): void {
  // Do not de-duplicate by URL; users may search/open different targets rapidly
  // Use a per-URL map only to focus existing if identical URL is requested twice in a row
  if (openWebWindows[url] && !openWebWindows[url].isDestroyed()) {
    openWebWindows[url].focus();
    return;
  }

  let webWindow: BrowserWindow | null = new BrowserWindow({
    width: 1024,
    height: 768,
    show: false,
    parent: mainWindow || undefined,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  webWindow.loadURL(url);

  openWebWindows[url] = webWindow;

  webWindow.once('ready-to-show', () => {
    if (webWindow && !webWindow.isDestroyed()) webWindow.show();
  });

  webWindow.on('focus', () => {
    if (webWindow && !webWindow.isDestroyed()) webWindow.moveTop();
  });

  webWindow.on('closed', () => {
    openWebWindows[url] = null;
    // Remove from external windows tracking
    externalWindows = externalWindows.filter(win => win !== webWindow);
    webWindow = null;
  });

  // Track external window for selection monitoring
  externalWindows.push(webWindow);

  // Allow multiple subsequent popups of different URLs without blocking by the map
  setTimeout(() => {
    openWebWindows[url] = null;
  }, 1000);
}


// Create a dedicated dictionary window (expanded) that uses the popup renderer entry
function createDictionaryWindow(term: string): void {
  let dictWindow: BrowserWindow | null = new BrowserWindow({
    width: 820,
    height: 620,
    show: false,
    parent: mainWindow || undefined,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Seed selection so renderer can render immediately
  lastSelectionEvent = selectionToContext(term, 0, 0, 'manual');

  // Use popup renderer but force #popup so it renders dictionary layout expanded
  const expandedUrl = withPopupDevFlag(POPUP_WINDOW_WEBPACK_ENTRY) + '#popup';
  dictWindow.loadURL(expandedUrl).catch(() => {});

  dictWindow.once('ready-to-show', () => {
    if (dictWindow && !dictWindow.isDestroyed()) dictWindow.show();
  });

  dictWindow.on('closed', () => {
    dictWindow = null;
  });
}
